[
  {
    "properties": {
      "name": "Reuters News XLS Input Module",
      "path to xls file": "src\\test\\resources\\News_filtered_DE_1.1.xls"
    },
    "moduleInstanceHashCode": 182985373,
    "moduleCanonicalClassName": "modules.weka_classifier.ReutersNewsXLSInputModule",
    "serializableInputPortList": {},
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 42770192,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "1550139548": "modules.CharPipe",
          "1796927575": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 18,
      "xpos": 29
    }
  },
  {
    "properties": {
      "name": "Weka Classifier Wrapper Module",
      "trainingdatafile": "src\\test\\resources\\trainingData.json",
      "method": "NaiveBayes"
    },
    "moduleInstanceHashCode": 60729411,
    "moduleCanonicalClassName": "modules.weka_classifier.WekaClassifierWrapperModule",
    "serializableInputPortList": {
      "article objects in json": {
        "instanceHashCode": 1550139548,
        "name": "article objects in json",
        "connectedPipesDestinationHashCodes": {
          "42770192": "modules.CharPipe"
        }
      },
      "json": {
        "instanceHashCode": 764854606,
        "name": "json",
        "connectedPipesDestinationHashCodes": {}
      },
      "text": {
        "instanceHashCode": 1258598387,
        "name": "text",
        "connectedPipesDestinationHashCodes": {}
      }
    },
    "serializableOutputPortList": {
      "json": {
        "instanceHashCode": 2007000716,
        "name": "json",
        "connectedPipesDestinationHashCodes": {
          "28817732": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 83,
      "xpos": 256
    }
  },
  {
    "properties": {
      "name": "Resolve Classification Module",
      "training data": "src\\test\\resources\\trainingData.json"
    },
    "moduleInstanceHashCode": 871803289,
    "moduleCanonicalClassName": "modules.weka_classifier.ResolveClassificationModule",
    "serializableInputPortList": {
      "Result of WekaClassifier Wrapper module": {
        "instanceHashCode": 28817732,
        "name": "Result of WekaClassifier Wrapper module",
        "connectedPipesDestinationHashCodes": {
          "2007000716": "modules.CharPipe"
        }
      },
      "text input": {
        "instanceHashCode": 447775885,
        "name": "text input",
        "connectedPipesDestinationHashCodes": {}
      },
      "articles": {
        "instanceHashCode": 1796927575,
        "name": "articles",
        "connectedPipesDestinationHashCodes": {
          "42770192": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 1948633887,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "4540177": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 236,
      "xpos": 381
    }
  },
  {
    "properties": {
      "outputfile": "C:\\Users\\avogt\\output.txt",
      "Buffer length": "8192",
      "name": "File Writer",
      "Encoding": "UTF-8",
      "Use GZIP": "false"
    },
    "moduleInstanceHashCode": 44727949,
    "moduleCanonicalClassName": "modules.input_output.FileWriterModule",
    "serializableInputPortList": {
      "input": {
        "instanceHashCode": 4540177,
        "name": "input",
        "connectedPipesDestinationHashCodes": {
          "1948633887": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {},
    "metadata": {
      "ypos": 289,
      "xpos": 84
    }
  }
]