[
  {
    "properties": {
      "name": "Weka Classifier Wrapper Module",
      "trainingdatafile": "src/test/resources/trainingData.json",
      "method": "NB"
    },
    "moduleInstanceHashCode": 888389963,
    "moduleCanonicalClassName": "modules.weka_classifier.WekaClassifierWrapperModule",
    "serializableInputPortList": {
      "bag of words": {
        "instanceHashCode": 1202070091,
        "name": "bag of words",
        "connectedPipesDestinationHashCodes": {}
      },
      "text": {
        "instanceHashCode": 992284558,
        "name": "text",
        "connectedPipesDestinationHashCodes": {}
      },
      "xls": {
        "instanceHashCode": 693880600,
        "name": "xls",
        "connectedPipesDestinationHashCodes": {
          "1070172405": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {
      "json": {
        "instanceHashCode": 1225478461,
        "name": "json",
        "connectedPipesDestinationHashCodes": {
          "1522626285": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 54,
      "xpos": 255
    }
  },
  {
    "properties": {
      "name": "Reuters News XLS Input Module",
      "path to xls file": "src/test/resources/News_filtered_DE_1.1.xls"
    },
    "moduleInstanceHashCode": 205164256,
    "moduleCanonicalClassName": "modules.weka_classifier.ReutersNewsXLSInputModule",
    "serializableInputPortList": {},
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 1070172405,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "693880600": "modules.CharPipe",
          "768934314": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 35,
      "xpos": 28
    }
  },
  {
    "properties": {
      "name": "Resolve Classification Module",
      "training data": "src/test/resources/trainingData.json"
    },
    "moduleInstanceHashCode": 1671089546,
    "moduleCanonicalClassName": "modules.weka_classifier.ResolveClassificationModule",
    "serializableInputPortList": {
      "Result of WekaClassifier Wrapper module": {
        "instanceHashCode": 1522626285,
        "name": "Result of WekaClassifier Wrapper module",
        "connectedPipesDestinationHashCodes": {
          "1225478461": "modules.CharPipe"
        }
      },
      "text input": {
        "instanceHashCode": 1588112069,
        "name": "text input",
        "connectedPipesDestinationHashCodes": {}
      },
      "articles": {
        "instanceHashCode": 768934314,
        "name": "articles",
        "connectedPipesDestinationHashCodes": {
          "1070172405": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 1304005268,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "475935688": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 220,
      "xpos": 293
    }
  },
  {
    "properties": {
      "outputfile": "C:\\Users\\avogt\\output.txt",
      "Buffer length": "8192",
      "name": "File Writer",
      "Encoding": "UTF-8",
      "Use GZIP": "false"
    },
    "moduleInstanceHashCode": 1509141062,
    "moduleCanonicalClassName": "modules.input_output.FileWriterModule",
    "serializableInputPortList": {
      "input": {
        "instanceHashCode": 475935688,
        "name": "input",
        "connectedPipesDestinationHashCodes": {
          "1304005268": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {},
    "metadata": {
      "ypos": 343,
      "xpos": 271
    }
  }
]