[
  {
    "properties": {
      "name": "Weka Classifier Wrapper Module",
      "trainingdatafile": "src/test/resources/trainingData.json",
      "method": "NB"
    },
    "moduleInstanceHashCode": 1192051224,
    "moduleCanonicalClassName": "modules.weka_classifier.WekaClassifierWrapperModule",
    "serializableInputPortList": {
      "bag of words": {
        "instanceHashCode": 666322419,
        "name": "bag of words",
        "connectedPipesDestinationHashCodes": {}
      },
      "text": {
        "instanceHashCode": 1012824344,
        "name": "text",
        "connectedPipesDestinationHashCodes": {
          "1368892880": "modules.CharPipe"
        }
      },
      "xls": {
        "instanceHashCode": 159202099,
        "name": "xls",
        "connectedPipesDestinationHashCodes": {}
      }
    },
    "serializableOutputPortList": {
      "json": {
        "instanceHashCode": 343441202,
        "name": "json",
        "connectedPipesDestinationHashCodes": {
          "1537294876": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 54,
      "xpos": 255
    }
  },
  {
    "properties": {
      "name": "Resolve Classification Module",
      "training data": "src/test/resources/trainingData.json"
    },
    "moduleInstanceHashCode": 1880212580,
    "moduleCanonicalClassName": "modules.weka_classifier.ResolveClassificationModule",
    "serializableInputPortList": {
      "Result of WekaClassifier Wrapper module": {
        "instanceHashCode": 1537294876,
        "name": "Result of WekaClassifier Wrapper module",
        "connectedPipesDestinationHashCodes": {
          "343441202": "modules.CharPipe"
        }
      },
      "text input": {
        "instanceHashCode": 930399645,
        "name": "text input",
        "connectedPipesDestinationHashCodes": {
          "1368892880": "modules.CharPipe"
        }
      },
      "articles": {
        "instanceHashCode": 1462818019,
        "name": "articles",
        "connectedPipesDestinationHashCodes": {}
      }
    },
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 15118552,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "1367778170": "modules.CharPipe"
        }
      }
    },
    "metadata": {
      "ypos": 220,
      "xpos": 293
    }
  },
  {
    "properties": {
      "outputfile": "C:\\Users\\avogt\\output.txt",
      "Buffer length": "8192",
      "name": "File Writer",
      "Encoding": "UTF-8",
      "Use GZIP": "false"
    },
    "moduleInstanceHashCode": 1840952098,
    "moduleCanonicalClassName": "modules.input_output.FileWriterModule",
    "serializableInputPortList": {
      "input": {
        "instanceHashCode": 1367778170,
        "name": "input",
        "connectedPipesDestinationHashCodes": {
          "15118552": "modules.CharPipe"
        }
      }
    },
    "serializableOutputPortList": {},
    "metadata": {
      "ypos": 343,
      "xpos": 271
    }
  },
  {
    "properties": {
      "Buffer length": "8192",
      "name": "File Reader",
      "inputfile": "/Users/andreas/git/stringsnstructures/src/test/resources/articles.txt",
      "Encoding": "UTF-8",
      "Normalize Unicode": "true",
      "Use GZIP": "false"
    },
    "moduleInstanceHashCode": 887480265,
    "moduleCanonicalClassName": "modules.input_output.FileReaderModule",
    "serializableInputPortList": {},
    "serializableOutputPortList": {
      "output": {
        "instanceHashCode": 1368892880,
        "name": "output",
        "connectedPipesDestinationHashCodes": {
          "1012824344": "modules.CharPipe",
          "930399645": "modules.CharPipe"
        }
      }
    },
    "metadata": {}
  }
]